---
include:
  - board: nice_nano//zmk
    shield: flatcat_left
    snippet: studio-rpc-usb-uart
    artifact-name: flatcat-split-left
  - board: nice_nano//zmk
    shield: flatcat_right
    artifact-name: flatcat-split-right
