---
include:
  - board: nice_nano//zmk
    shield: flatcat
    snippet: studio-rpc-usb-uart
<<<<<<< HEAD
    artifact-name: flatcat
=======
    artifact-name: flatcat-split-left
  - board: nice_nano//zmk
    shield: flatcat_right
    artifact-name: flatcat-split-right
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings-reset
>>>>>>> d01946c7509472e01dc75a3d8fb9b70542931743
